    <footer>
        <section class="contact">
            <h2 id="contact">Contact</h2>
            <?php if($send) : ?>
                <h2>Votre message a bien été envoyé. Je vous recontacte rapidement !</h2>
            <?php else : ?>
                <form action="#contact" method="POST">
                    <input type="email" name="email" placeholder="Votre e-mail" class="email">
                    <textarea name="message" cols="20" rows="20" placeholder="On garde le contact ?" class="message"></textarea>
                    <button type="submit">Envoyer</button>
                </form>
            <?php endif; ?>
        </section>
    </footer>
    <div class='scroll-to-top'>
        <a href='#'><img src="../assets/img/Xwing.png" alt=""></a>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="../assets/js/script.js"></script>
</body>
</html>